export { default as TopHeader } from '@/components/common/TopHeader.vue'
export { default as MainHeader } from '@/components/common/MainHeader.vue'
export { default as Footer } from '@/components/common/Footer.vue'

export { default as ComingSoon } from '@/components/comming-soon/CommingSoon.vue'

// Home Page Component
export { default as HomeSlider } from '@/components/layout/HomeSlider.vue'
export { default as HotelOperationsManagement } from '@/components/layout/HotelOperationsManagement.vue'
export { default as StaffingServices } from '@/components/layout/StaffingServices.vue'
export { default as StaffingSolutions } from '@/components/layout/StaffingSolutions.vue'
export { default as PartnersBenefits } from '@/components/layout/PartnersBenefits.vue'
export { default as WhyPeopleChooseUs } from '@/components/layout/WhyPeopleChooseUs.vue'
export { default as WhoWeAre } from '@/components/layout/WhoWeAre.vue'
export { default as TechSavvy } from '@/components/layout/TechSavvy.vue'
export { default as OurTeam } from '@/components/layout/OurTeam.vue'
export { default as ClientsTestimonial } from '@/components/layout/ClientsTestimonial.vue'
export { default as OurPartners } from '@/components/layout/OurPartners.vue'
export { default as YearsOfExpreience } from '@/components/layout/YearsOfExpreience.vue'
export { default as OurStaffingProcess } from '@/components/layout/OurStaffingProcess.vue'
export { default as PageBanner } from '@/components/layout/PageBanner.vue'
export { default as WhyChooseUs } from '@/components/layout/WhyChooseUs.vue'
export { default as OurStaffTraining } from '@/components/layout/OurStaffTraining.vue'
export { default as OurWorkingProcess } from '@/components/layout/OurWorkingProcess.vue'
export { default as HousekeepingManagement } from '@/components/layout/HousekeepingManagement.vue'
export { default as ProjectManagement } from '@/components/layout/ProjectManagement.vue'
export { default as UnderDevelopment } from '@/components/layout/UnderDevelopment.vue'
export { default as ComprehensiveHousekeepingManagement } from '@/components/layout/ComprehensiveHousekeepingManagement.vue'
export { default as ContactForm } from '@/components/layout/ContactForm.vue'
export { default as ContactLocationMap } from '@/components/layout/ContactLocationMap.vue'
export { default as JobPostCard } from '@/components/layout/JobPostCard.vue'

export { default as FacilityManagement } from '@/components/layout/FacilityManagement.vue'
export { default as HumanResourceManagement } from '@/components/layout/HumanResourceManagement.vue' 
export { default as MaintenanceManagement } from '@/components/layout/MaintenanceManagement.vue'
export { default as HealthSafetyManagement } from '@/components/layout/HealthSafetyManagement.vue'
export { default as FoodBevarageManagement } from '@/components/layout/FoodBevarageManagement.vue'
export { default as KitchenManagement } from '@/components/layout/KitchenManagement.vue'
export { default as FrontDeskManagement } from '@/components/layout/FrontDeskManagement.vue'
export { default as CleaningManagement } from '@/components/layout/CleaningManagement.vue'
export { default as ItManagement } from '@/components/layout/ItManagement.vue'
export { default as LaserSpaManagement } from '@/components/layout/LaserSpaManagement.vue'
export { default as HospitalityOperationManagement } from '@/components/layout/HospitalityOperationManagement.vue'
export { default as MarketingManagement } from '@/components/layout/MarketingManagement.vue'
export { default as HospitalityInvestmentFeasibility } from '@/components/layout/HospitalityInvestmentFeasibility.vue'
export { default as RevenueYieldManagement } from '@/components/layout/RevenueYieldManagement.vue'
export { default as CareerManagement } from '@/components/layout/CareerManagement.vue'